var group__OPEND__HANFUN__PROFILE =
[
    [ "openD HAN-FUN API pSimpleLevelControllable", "group__OPEND__HANFUN__API__PSIMPLELEVELCONTROLLABLE.html", "group__OPEND__HANFUN__API__PSIMPLELEVELCONTROLLABLE" ],
    [ "openD HAN-FUN API pSimpleOnOffSwitchable", "group__OPEND__HANFUN__API__PSIMPLEONOFFSWITCHABLE.html", "group__OPEND__HANFUN__API__PSIMPLEONOFFSWITCHABLE" ]
];